apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-db-deployment
  labels:
    app: auth-db
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-db
  template:
    metadata:
      labels:
        app: auth-db
    spec:
      containers:
      - name: auth-postgres
        image: postgres:9.6
        ports:
        - containerPort: 5432
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 250m
            memory: 256Mi
        env:
        - name: POSTGRES_DB
          value: "devheaven"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
                name: auth-db
                key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
                name: auth-db
                key: password
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: auth-postgres-pvc