apiVersion: v1
kind: Service
metadata:
  name: hour-db-service
  labels:
    app: hour-db
  namespace: staging
spec:
  type: ClusterIP
  ports:
  - name: mongo
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: hour-db