apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
  name: gateway
  namespace: production
spec:
  rules:
  - host: devheaven.nl
    http:
      paths:
      - backend:
          serviceName: frontend-service
          servicePort: 80
        path: /