apiVersion: v1
kind: Service
metadata:
  name: task-management-db-service
  labels:
    app: task-management-db
  namespace: production
spec:
  type: ClusterIP
  ports:
  - name: mongo
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: task-management-db